export const USERS = {
  admin: ['dy_se'],
  ecomm: [
    {
      user_id: '1',
      Name: 'Sara Khan',
      DisplayName: 'Sara',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '2110',
      Location: 'London, United Kingdom',
      MembershipNumber: 'BRONZE-5623981',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Moschino Teddy Bear Knit Hat',
      RecentPurchaseSku: '214665640',
    },
    {
      user_id: '2',
      Name: 'John Lee',
      DisplayName: 'John',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '5380',
      Location: 'Sydney, Australia',
      MembershipNumber: 'SILVER-1093845',
      ProductInterests: 'Fitness, Electronics, Books',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '3',
      Name: 'Alex Smith',
      DisplayName: 'Alex',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '12450',
      Location: 'Toronto, Canada',
      MembershipNumber: 'GOLD-4582139',
      ProductInterests: 'Electronics, Home & Garden, Sports',
      RecentPurchaseName: 'Grigio Soap Dish',
      RecentPurchaseSku: '213701113',
    },
    {
      user_id: '4',
      Name: 'Maria Lopez',
      DisplayName: 'Maria',
      LoyaltyLevel: 'Platinum',
      LoyaltyPoints: '23890',
      Location: 'Madrid, Spain',
      MembershipNumber: 'PLATINUM-7921402',
      ProductInterests: 'Fashion, Skincare, Travel Gear',
      RecentPurchaseName: 'Logo Charm Pouch',
      RecentPurchaseSku: '214663159',
    },
    {
      user_id: '5',
      Name: 'Emma Davis',
      DisplayName: 'Emma',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '11970',
      Location: 'Cape Town, South Africa',
      MembershipNumber: 'GOLD-3721984',
      ProductInterests: 'Kitchenware, Fitness, Books',
      RecentPurchaseName: 'Air Fryer',
      RecentPurchaseSku: '',
    },
    {
      user_id: '6',
      Name: 'Daniel Chen',
      DisplayName: 'Daniel',
      LoyaltyLevel: 'Platinum',
      LoyaltyPoints: '25340',
      Location: 'Singapore',
      MembershipNumber: 'PLATINUM-9134872',
      ProductInterests: 'Tech Gadgets, Travel Accessories',
      RecentPurchaseName: 'Noise-Cancelling Earbuds',
      RecentPurchaseSku: '',
    },
    {
      user_id: '7',
      Name: 'Lucy Patel',
      DisplayName: 'Lucy',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '6520',
      Location: 'London, United Kingdom',
      MembershipNumber: 'SILVER-8239140',
      ProductInterests: 'Fashion, Skincare, Jewelry',
      RecentPurchaseName: 'Silk Scarf',
      RecentPurchaseSku: '',
    },
    {
      user_id: '8',
      Name: 'Adam Brown',
      DisplayName: 'Adam',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '1860',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'BRONZE-7219083',
      ProductInterests: 'Tools, Gardening, Books',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '9',
      Name: 'Nina Park',
      DisplayName: 'Nina',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '13760',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'GOLD-6501928',
      ProductInterests: 'K-Beauty, Tech, Fashion',
      RecentPurchaseName: 'Facial Cleansing Brush',
      RecentPurchaseSku: '',
    },
    {
      user_id: '10',
      Name: 'Leo Martin',
      DisplayName: 'Leo',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '7200',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'SILVER-3982011',
      ProductInterests: 'Sports, Casualwear, Electronics',
      RecentPurchaseName: 'Running Shoes',
      RecentPurchaseSku: '',
    },
    {
      user_id: '11',
      Name: 'Anya Garcia',
      DisplayName: 'Anya',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '8524',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'SILVER-2719583',
      ProductInterests: 'Books, Music',
      RecentPurchaseName: 'Plant Pot Set',
      RecentPurchaseSku: '215423456',
    },
    {
      user_id: '12',
      Name: 'Ines Laurent',
      DisplayName: 'Ines',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '1541',
      Location: 'London, United Kingdom',
      MembershipNumber: 'SILVER-4903402',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Silk Scarf',
      RecentPurchaseSku: '',
    },
    {
      user_id: '13',
      Name: 'Sakura Lebedev',
      DisplayName: 'Sakura',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '7015',
      Location: 'Buenos Aires, Argentina',
      MembershipNumber: 'BRONZE-8536477',
      ProductInterests: 'Outdoor, Camping',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '14',
      Name: 'Beatriz Murphy',
      DisplayName: 'Beatriz',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '712',
      Location: 'Singapore',
      MembershipNumber: 'SILVER-5661907',
      ProductInterests: 'Outdoor, Camping',
      RecentPurchaseName: 'Leather Tote Bag',
      RecentPurchaseSku: '214712345',
    },
    {
      user_id: '15',
      Name: 'Diego Petrov',
      DisplayName: 'Diego',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '11529',
      Location: 'Madrid, Spain',
      MembershipNumber: 'GOLD-2622631',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Yoga Mat',
      RecentPurchaseSku: '214801234',
    },
    {
      user_id: '16',
      Name: 'Matteo Siddiqui',
      DisplayName: 'Matteo',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '26947',
      Location: 'Sydney, Australia',
      MembershipNumber: 'SILVER-3094235',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: 'Wireless Mouse',
      RecentPurchaseSku: '215098765',
    },
    {
      user_id: '17',
      Name: 'Camille Rossi',
      DisplayName: 'Camille',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '27677',
      Location: 'Bangkok, Thailand',
      MembershipNumber: 'SILVER-4226067',
      ProductInterests: 'Tools, Gardening',
      RecentPurchaseName: 'Perfume Set',
      RecentPurchaseSku: '215134567',
    },
    {
      user_id: '18',
      Name: 'Fatima Müller',
      DisplayName: 'Fatima',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '25831',
      Location: 'Tokyo, Japan',
      MembershipNumber: 'SILVER-4905582',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Ceramic Mug Set',
      RecentPurchaseSku: '215667890',
    },
    {
      user_id: '19',
      Name: 'Chloe Hayashi',
      DisplayName: 'Chloe',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '21330',
      Location: 'Berlin, Germany',
      MembershipNumber: 'BRONZE-6960453',
      ProductInterests: 'Travel, Accessories',
      RecentPurchaseName: 'Smart Watch',
      RecentPurchaseSku: '214798001',
    },
    {
      user_id: '20',
      Name: 'Layla Brennan',
      DisplayName: 'Layla',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '22898',
      Location: 'Toronto, Canada',
      MembershipNumber: 'BRONZE-3871230',
      ProductInterests: 'Food & Beverage, Kitchenware',
      RecentPurchaseName: 'Sunglasses',
      RecentPurchaseSku: '215267890',
    },
    {
      user_id: '21',
      Name: 'Nikos Svensson',
      DisplayName: 'Nikos',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '12933',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'BRONZE-6440561',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '22',
      Name: 'Pierre Nkosi',
      DisplayName: 'Pierre',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '26879',
      Location: 'Paris, France',
      MembershipNumber: 'SILVER-2110460',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Facial Cleansing Brush',
      RecentPurchaseSku: '',
    },
    {
      user_id: '23',
      Name: 'Antoine Guerrero',
      DisplayName: 'Antoine',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '10811',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'GOLD-8698256',
      ProductInterests: 'Skincare, Wellness',
      RecentPurchaseName: 'Yoga Mat',
      RecentPurchaseSku: '214801234',
    },
    {
      user_id: '24',
      Name: 'Amara Nakamura',
      DisplayName: 'Amara',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '24911',
      Location: 'Buenos Aires, Argentina',
      MembershipNumber: 'BRONZE-8187926',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Facial Cleansing Brush',
      RecentPurchaseSku: '',
    },
    {
      user_id: '25',
      Name: 'Sven Eriksson',
      DisplayName: 'Sven',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '5032',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'BRONZE-1790481',
      ProductInterests: 'Skincare, Wellness',
      RecentPurchaseName: 'Grigio Soap Dish',
      RecentPurchaseSku: '213701113',
    },
    {
      user_id: '26',
      Name: 'Anya Chen',
      DisplayName: 'Anya',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '26454',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'SILVER-7455324',
      ProductInterests: 'Food & Beverage, Kitchenware',
      RecentPurchaseName: 'Grigio Soap Dish',
      RecentPurchaseSku: '213701113',
    },
    {
      user_id: '27',
      Name: 'Camille Vega',
      DisplayName: 'Camille',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '17838',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'GOLD-1192619',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Ceramic Mug Set',
      RecentPurchaseSku: '215667890',
    },
    {
      user_id: '28',
      Name: 'Anya Novikov',
      DisplayName: 'Anya',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '25104',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'GOLD-5924115',
      ProductInterests: 'Casualwear, Footwear',
      RecentPurchaseName: 'Logo Charm Pouch',
      RecentPurchaseSku: '214663159',
    },
    {
      user_id: '29',
      Name: 'Lars Williams',
      DisplayName: 'Lars',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '24161',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'BRONZE-3997281',
      ProductInterests: 'Gaming, Electronics',
      RecentPurchaseName: 'Board Game',
      RecentPurchaseSku: '215489012',
    },
    {
      user_id: '30',
      Name: 'Sakura Tanaka',
      DisplayName: 'Sakura',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '10279',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'GOLD-3564217',
      ProductInterests: 'Food & Beverage, Kitchenware',
      RecentPurchaseName: 'Silk Scarf',
      RecentPurchaseSku: '',
    },
    {
      user_id: '31',
      Name: 'Andrei Williams',
      DisplayName: 'Andrei',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '26014',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-6438436',
      ProductInterests: 'Fashion, Skincare',
      RecentPurchaseName: 'Linen Dress',
      RecentPurchaseSku: '215201234',
    },
    {
      user_id: '32',
      Name: 'Aurora Johansson',
      DisplayName: 'Aurora',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '12394',
      Location: 'Tokyo, Japan',
      MembershipNumber: 'BRONZE-5041154',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '33',
      Name: 'Piotr Rossi',
      DisplayName: 'Piotr',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '16424',
      Location: 'Toronto, Canada',
      MembershipNumber: 'BRONZE-3109911',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Board Game',
      RecentPurchaseSku: '215489012',
    },
    {
      user_id: '34',
      Name: 'Priya Raza',
      DisplayName: 'Priya',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '18515',
      Location: 'Singapore',
      MembershipNumber: 'BRONZE-8099076',
      ProductInterests: 'Avant-Garde, Streetwear',
      RecentPurchaseName: 'Slim Fit Chinos',
      RecentPurchaseSku: '215034567',
    },
    {
      user_id: '35',
      Name: 'Antoine Bah',
      DisplayName: 'Antoine',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '23105',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'SILVER-7264956',
      ProductInterests: 'K-Beauty, Skincare',
      RecentPurchaseName: 'Yoga Mat',
      RecentPurchaseSku: '214801234',
    },
    {
      user_id: '36',
      Name: 'Miriam Jiménez',
      DisplayName: 'Miriam',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '8623',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'BRONZE-1352896',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Leather Tote Bag',
      RecentPurchaseSku: '214712345',
    },
    {
      user_id: '37',
      Name: 'Beatriz Pereira',
      DisplayName: 'Beatriz',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '7716',
      Location: 'London, United Kingdom',
      MembershipNumber: 'BRONZE-1987737',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '38',
      Name: 'Marco Kim',
      DisplayName: 'Marco',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '28668',
      Location: 'Paris, France',
      MembershipNumber: 'GOLD-4993055',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Slim Fit Chinos',
      RecentPurchaseSku: '215034567',
    },
    {
      user_id: '39',
      Name: 'Felix Brennan',
      DisplayName: 'Felix',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '18169',
      Location: 'Cape Town, South Africa',
      MembershipNumber: 'BRONZE-8930103',
      ProductInterests: 'Baby & Maternity, Kids',
      RecentPurchaseName: 'Perfume Set',
      RecentPurchaseSku: '215134567',
    },
    {
      user_id: '40',
      Name: 'Oscar Oliveira',
      DisplayName: 'Oscar',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '6739',
      Location: 'Madrid, Spain',
      MembershipNumber: 'SILVER-8231838',
      ProductInterests: 'Fitness, Sports',
      RecentPurchaseName: 'Backpack',
      RecentPurchaseSku: '215312345',
    },
    {
      user_id: '41',
      Name: 'Matteo Kaur',
      DisplayName: 'Matteo',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '28806',
      Location: 'Sydney, Australia',
      MembershipNumber: 'BRONZE-7754864',
      ProductInterests: 'Fitness, Sports',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '42',
      Name: 'Finn Tanaka',
      DisplayName: 'Finn',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '6732',
      Location: 'Buenos Aires, Argentina',
      MembershipNumber: 'BRONZE-8077999',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: 'Air Fryer',
      RecentPurchaseSku: '',
    },
    {
      user_id: '43',
      Name: 'Rafael Murphy',
      DisplayName: 'Rafael',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '29155',
      Location: 'Toronto, Canada',
      MembershipNumber: 'BRONZE-2642635',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: 'Protein Powder',
      RecentPurchaseSku: '215534567',
    },
    {
      user_id: '44',
      Name: 'Yuki Tanaka',
      DisplayName: 'Yuki',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '27894',
      Location: 'London, United Kingdom',
      MembershipNumber: 'GOLD-4965789',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Phone Case',
      RecentPurchaseSku: '215778901',
    },
    {
      user_id: '45',
      Name: 'Sebastian Romero',
      DisplayName: 'Sebastian',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '7504',
      Location: 'New York, United States',
      MembershipNumber: 'BRONZE-7358113',
      ProductInterests: 'Electronics, Tech',
      RecentPurchaseName: 'Noise-Cancelling Earbuds',
      RecentPurchaseSku: '',
    },
    {
      user_id: '46',
      Name: 'Olivia Diallo',
      DisplayName: 'Olivia',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '26192',
      Location: 'Dubai, United Arab Emirates',
      MembershipNumber: 'BRONZE-9164991',
      ProductInterests: 'K-Beauty, Skincare',
      RecentPurchaseName: 'Cashmere Sweater',
      RecentPurchaseSku: '214856789',
    },
    {
      user_id: '47',
      Name: 'Diego Hassan',
      DisplayName: 'Diego',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '2416',
      Location: 'Mumbai, India',
      MembershipNumber: 'BRONZE-6261415',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '48',
      Name: 'Pierre Patel',
      DisplayName: 'Pierre',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '16977',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-9519948',
      ProductInterests: 'Travel, Accessories',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '49',
      Name: 'Isabelle Berg',
      DisplayName: 'Isabelle',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '2726',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'BRONZE-5130808',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Logo Charm Pouch',
      RecentPurchaseSku: '214663159',
    },
    {
      user_id: '50',
      Name: 'Sven Vega',
      DisplayName: 'Sven',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '3186',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'BRONZE-9770838',
      ProductInterests: 'Baby & Maternity, Kids',
      RecentPurchaseName: 'Perfume Set',
      RecentPurchaseSku: '215134567',
    },
    {
      user_id: '51',
      Name: 'Amelia Nakamura',
      DisplayName: 'Amelia',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '23968',
      Location: 'Paris, France',
      MembershipNumber: 'BRONZE-7640184',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: 'Facial Cleansing Brush',
      RecentPurchaseSku: '',
    },
    {
      user_id: '52',
      Name: 'Priya Brennan',
      DisplayName: 'Priya',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '15482',
      Location: 'Paris, France',
      MembershipNumber: 'SILVER-8688755',
      ProductInterests: 'Kids & Toys, Home Decor',
      RecentPurchaseName: 'Moschino Teddy Bear Knit Hat',
      RecentPurchaseSku: '214665640',
    },
    {
      user_id: '53',
      Name: 'Luisa Guerrero',
      DisplayName: 'Luisa',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '2900',
      Location: 'Buenos Aires, Argentina',
      MembershipNumber: 'GOLD-5449324',
      ProductInterests: 'Home & Garden, Kitchenware',
      RecentPurchaseName: 'Slim Fit Chinos',
      RecentPurchaseSku: '215034567',
    },
    {
      user_id: '54',
      Name: 'Priya Siddiqui',
      DisplayName: 'Priya',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '29311',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'GOLD-3646552',
      ProductInterests: 'Tools, Gardening',
      RecentPurchaseName: 'Running Shoes',
      RecentPurchaseSku: '',
    },
    {
      user_id: '55',
      Name: 'Miriam Bah',
      DisplayName: 'Miriam',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '20543',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-6022741',
      ProductInterests: 'Fashion, Skincare',
      RecentPurchaseName: 'Backpack',
      RecentPurchaseSku: '215312345',
    },
    {
      user_id: '56',
      Name: 'Ethan Ivanov',
      DisplayName: 'Ethan',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '29654',
      Location: 'Madrid, Spain',
      MembershipNumber: 'BRONZE-5569244',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Air Fryer',
      RecentPurchaseSku: '',
    },
    {
      user_id: '57',
      Name: 'Serena Lebedev',
      DisplayName: 'Serena',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '11735',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'BRONZE-9196204',
      ProductInterests: 'Avant-Garde, Streetwear',
      RecentPurchaseName: 'Slim Fit Chinos',
      RecentPurchaseSku: '215034567',
    },
    {
      user_id: '58',
      Name: 'Nadia Patel',
      DisplayName: 'Nadia',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '14379',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'BRONZE-6596150',
      ProductInterests: 'Electronics, Tech',
      RecentPurchaseName: 'Moschino Teddy Bear Knit Hat',
      RecentPurchaseSku: '214665640',
    },
    {
      user_id: '59',
      Name: 'Priya Gustafsson',
      DisplayName: 'Priya',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '5794',
      Location: 'Dubai, United Arab Emirates',
      MembershipNumber: 'GOLD-8175395',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '60',
      Name: 'Charlotte Smith',
      DisplayName: 'Charlotte',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '29437',
      Location: 'Cape Town, South Africa',
      MembershipNumber: 'BRONZE-7194416',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '61',
      Name: 'Sven Pereira',
      DisplayName: 'Sven',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '4676',
      Location: 'Sydney, Australia',
      MembershipNumber: 'BRONZE-1669324',
      ProductInterests: 'K-Beauty, Skincare',
      RecentPurchaseName: 'Smart Watch',
      RecentPurchaseSku: '214798001',
    },
    {
      user_id: '62',
      Name: 'Matteo Navarro',
      DisplayName: 'Matteo',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '22354',
      Location: 'Madrid, Spain',
      MembershipNumber: 'SILVER-7817881',
      ProductInterests: 'Tools, Gardening',
      RecentPurchaseName: 'Board Game',
      RecentPurchaseSku: '215489012',
    },
    {
      user_id: '63',
      Name: 'Luisa Chen',
      DisplayName: 'Luisa',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '8257',
      Location: 'Singapore',
      MembershipNumber: 'GOLD-7917152',
      ProductInterests: 'Travel, Accessories',
      RecentPurchaseName: 'Beanie Hat',
      RecentPurchaseSku: '215712345',
    },
    {
      user_id: '64',
      Name: 'Carlos Santos',
      DisplayName: 'Carlos',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '11385',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'SILVER-3670896',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: 'Facial Cleansing Brush',
      RecentPurchaseSku: '',
    },
    {
      user_id: '65',
      Name: 'Ethan Hayashi',
      DisplayName: 'Ethan',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '28634',
      Location: 'Amsterdam, Netherlands',
      MembershipNumber: 'GOLD-8722606',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: 'Silk Scarf',
      RecentPurchaseSku: '',
    },
    {
      user_id: '66',
      Name: 'Leila Mensah',
      DisplayName: 'Leila',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '29051',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'SILVER-4240180',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: 'Moschino Teddy Bear Knit Hat',
      RecentPurchaseSku: '214665640',
    },
    {
      user_id: '67',
      Name: 'Callum Torres',
      DisplayName: 'Callum',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '2774',
      Location: 'São Paulo, Brazil',
      MembershipNumber: 'BRONZE-9546409',
      ProductInterests: 'Tools, Gardening',
      RecentPurchaseName: 'Sunglasses',
      RecentPurchaseSku: '215267890',
    },
    {
      user_id: '68',
      Name: 'Callum Herrera',
      DisplayName: 'Callum',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '18070',
      Location: 'Paris, France',
      MembershipNumber: 'GOLD-5382463',
      ProductInterests: 'Fashion, Skincare',
      RecentPurchaseName: 'Logo Charm Pouch',
      RecentPurchaseSku: '214663159',
    },
    {
      user_id: '69',
      Name: 'Ingrid Malik',
      DisplayName: 'Ingrid',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '9198',
      Location: 'Sydney, Australia',
      MembershipNumber: 'GOLD-8290770',
      ProductInterests: 'Fitness, Sports',
      RecentPurchaseName: 'Linen Dress',
      RecentPurchaseSku: '215201234',
    },
    {
      user_id: '70',
      Name: 'Leila Alves',
      DisplayName: 'Leila',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '17258',
      Location: 'Madrid, Spain',
      MembershipNumber: 'BRONZE-4188992',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Beanie Hat',
      RecentPurchaseSku: '215712345',
    },
    {
      user_id: '71',
      Name: 'Nadia Müller',
      DisplayName: 'Nadia',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '555',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-4305700',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Backpack',
      RecentPurchaseSku: '215312345',
    },
    {
      user_id: '72',
      Name: 'Saoirse McCarthy',
      DisplayName: 'Saoirse',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '22265',
      Location: 'Paris, France',
      MembershipNumber: 'BRONZE-3090865',
      ProductInterests: 'Food & Beverage, Kitchenware',
      RecentPurchaseName: 'Leather Tote Bag',
      RecentPurchaseSku: '214712345',
    },
    {
      user_id: '73',
      Name: 'Clara Ahmed',
      DisplayName: 'Clara',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '13882',
      Location: 'Paris, France',
      MembershipNumber: 'BRONZE-5960271',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '74',
      Name: 'Elias Ferreira',
      DisplayName: 'Elias',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '22288',
      Location: 'New York, United States',
      MembershipNumber: 'BRONZE-6049101',
      ProductInterests: 'Travel, Accessories',
      RecentPurchaseName: 'Linen Dress',
      RecentPurchaseSku: '215201234',
    },
    {
      user_id: '75',
      Name: 'Callum Pereira',
      DisplayName: 'Callum',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '10457',
      Location: 'Tokyo, Japan',
      MembershipNumber: 'SILVER-6406444',
      ProductInterests: 'Home & Garden, Kitchenware',
      RecentPurchaseName: 'Cashmere Sweater',
      RecentPurchaseSku: '214856789',
    },
    {
      user_id: '76',
      Name: 'Dmitri Morales',
      DisplayName: 'Dmitri',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '7502',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'BRONZE-3846949',
      ProductInterests: 'Skincare, Wellness',
      RecentPurchaseName: 'Protein Powder',
      RecentPurchaseSku: '215534567',
    },
    {
      user_id: '77',
      Name: 'Isabelle Vargas',
      DisplayName: 'Isabelle',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '21240',
      Location: 'Bangkok, Thailand',
      MembershipNumber: 'SILVER-4940441',
      ProductInterests: 'Casualwear, Footwear',
      RecentPurchaseName: 'Grigio Soap Dish',
      RecentPurchaseSku: '213701113',
    },
    {
      user_id: '78',
      Name: 'Takeshi Yamamoto',
      DisplayName: 'Takeshi',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '5328',
      Location: 'London, United Kingdom',
      MembershipNumber: 'SILVER-8971465',
      ProductInterests: 'Electronics, Tech',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '79',
      Name: 'Axel Costa',
      DisplayName: 'Axel',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '29536',
      Location: 'Mumbai, India',
      MembershipNumber: 'BRONZE-7442089',
      ProductInterests: 'Home & Garden, Kitchenware',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '80',
      Name: 'Theo Eriksson',
      DisplayName: 'Theo',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '21997',
      Location: 'London, United Kingdom',
      MembershipNumber: 'BRONZE-8132769',
      ProductInterests: 'Fitness, Sports',
      RecentPurchaseName: 'Board Game',
      RecentPurchaseSku: '215489012',
    },
    {
      user_id: '81',
      Name: 'Zara Santos',
      DisplayName: 'Zara',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '23303',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-5180853',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '82',
      Name: 'Lucas Inoue',
      DisplayName: 'Lucas',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '15725',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'BRONZE-6323376',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Linen Dress',
      RecentPurchaseSku: '215201234',
    },
    {
      user_id: '83',
      Name: 'Miriam Kato',
      DisplayName: 'Miriam',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '29729',
      Location: 'Stockholm, Sweden',
      MembershipNumber: 'SILVER-8481188',
      ProductInterests: 'Outdoor, Camping',
      RecentPurchaseName: 'Desk Lamp',
      RecentPurchaseSku: '215601234',
    },
    {
      user_id: '84',
      Name: 'Valentina Oliveira',
      DisplayName: 'Valentina',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '25134',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'BRONZE-9745959',
      ProductInterests: 'Avant-Garde, Streetwear',
      RecentPurchaseName: 'Board Game',
      RecentPurchaseSku: '215489012',
    },
    {
      user_id: '85',
      Name: 'Aurora Ribeiro',
      DisplayName: 'Aurora',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '14913',
      Location: 'Toronto, Canada',
      MembershipNumber: 'BRONZE-5558623',
      ProductInterests: 'K-Beauty, Skincare',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '86',
      Name: 'Bianca Alves',
      DisplayName: 'Bianca',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '3140',
      Location: 'Cape Town, South Africa',
      MembershipNumber: 'GOLD-7426265',
      ProductInterests: 'Books, Music',
      RecentPurchaseName: 'Mini Tool Set',
      RecentPurchaseSku: '',
    },
    {
      user_id: '87',
      Name: 'Fatima Suzuki',
      DisplayName: 'Fatima',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '18280',
      Location: 'Dubai, United Arab Emirates',
      MembershipNumber: 'BRONZE-4470105',
      ProductInterests: 'Outdoor, Camping',
      RecentPurchaseName: '5.0 Low Vulcanized Sneakers',
      RecentPurchaseSku: '214653464',
    },
    {
      user_id: '88',
      Name: 'Ivan Diallo',
      DisplayName: 'Ivan',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '19639',
      Location: 'London, United Kingdom',
      MembershipNumber: 'GOLD-9002392',
      ProductInterests: 'Baby & Maternity, Kids',
      RecentPurchaseName: 'Yoga Mat',
      RecentPurchaseSku: '214801234',
    },
    {
      user_id: '89',
      Name: 'Olivia Walsh',
      DisplayName: 'Olivia',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '13279',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'BRONZE-4700025',
      ProductInterests: 'Art, Stationery',
      RecentPurchaseName: 'Plant Pot Set',
      RecentPurchaseSku: '215423456',
    },
    {
      user_id: '90',
      Name: 'Aurora Yamamoto',
      DisplayName: 'Aurora',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '16413',
      Location: 'London, United Kingdom',
      MembershipNumber: 'BRONZE-7783308',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Leather Tote Bag',
      RecentPurchaseSku: '214712345',
    },
    {
      user_id: '91',
      Name: 'Sebastian Traore',
      DisplayName: 'Sebastian',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '20890',
      Location: 'Buenos Aires, Argentina',
      MembershipNumber: 'GOLD-7610562',
      ProductInterests: 'Fashion, Skincare',
      RecentPurchaseName: 'Phone Case',
      RecentPurchaseSku: '215778901',
    },
    {
      user_id: '92',
      Name: 'Beatriz Guerrero',
      DisplayName: 'Beatriz',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '3250',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'SILVER-8746014',
      ProductInterests: 'Books, Music',
      RecentPurchaseName: 'Ceramic Mug Set',
      RecentPurchaseSku: '215667890',
    },
    {
      user_id: '93',
      Name: 'Rafael Patel',
      DisplayName: 'Rafael',
      LoyaltyLevel: 'Bronze',
      LoyaltyPoints: '11226',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'BRONZE-6662319',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: 'Leather Tote Bag',
      RecentPurchaseSku: '214712345',
    },
    {
      user_id: '94',
      Name: 'Camille Murphy',
      DisplayName: 'Camille',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '27760',
      Location: 'Mexico City, Mexico',
      MembershipNumber: 'SILVER-2374158',
      ProductInterests: 'Avant-Garde, Streetwear',
      RecentPurchaseName: 'Desk Lamp',
      RecentPurchaseSku: '215601234',
    },
    {
      user_id: '95',
      Name: 'Penelope Johansson',
      DisplayName: 'Penelope',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '2206',
      Location: 'Berlin, Germany',
      MembershipNumber: 'SILVER-2151225',
      ProductInterests: 'Jewelry, Watches',
      RecentPurchaseName: 'Sunglasses',
      RecentPurchaseSku: '215267890',
    },
    {
      user_id: '96',
      Name: 'Liam Garcia',
      DisplayName: 'Liam',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '7032',
      Location: 'London, United Kingdom',
      MembershipNumber: 'GOLD-5002120',
      ProductInterests: 'Food & Beverage, Kitchenware',
      RecentPurchaseName: 'Air Fryer',
      RecentPurchaseSku: '',
    },
    {
      user_id: '97',
      Name: 'Priya Oliveira',
      DisplayName: 'Priya',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '18980',
      Location: 'Dublin, Ireland',
      MembershipNumber: 'SILVER-5299055',
      ProductInterests: 'Pet Supplies, Home',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '98',
      Name: 'Andrei Dubois',
      DisplayName: 'Andrei',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '25008',
      Location: 'Madrid, Spain',
      MembershipNumber: 'SILVER-2813596',
      ProductInterests: 'Travel, Accessories',
      RecentPurchaseName: 'Running Shoes',
      RecentPurchaseSku: '',
    },
    {
      user_id: '99',
      Name: 'Sven Garcia',
      DisplayName: 'Sven',
      LoyaltyLevel: 'Gold',
      LoyaltyPoints: '19367',
      Location: 'New York, United States',
      MembershipNumber: 'GOLD-4327421',
      ProductInterests: 'Luxury Fashion, Bags',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
    {
      user_id: '100',
      Name: 'Noah Doyle',
      DisplayName: 'Noah',
      LoyaltyLevel: 'Silver',
      LoyaltyPoints: '21053',
      Location: 'Seoul, South Korea',
      MembershipNumber: 'SILVER-6059717',
      ProductInterests: 'Fitness, Sports',
      RecentPurchaseName: 'Neck Pillow',
      RecentPurchaseSku: '215378901',
    },
  ],
}
