import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  {
    name: 'Men',
    subcategories: ['Clothing', 'Shoes', 'Accessories', 'Watches', 'Grooming'],
  },
  {
    name: 'Women',
    subcategories: ['Clothing', 'Shoes', 'Handbags', 'Jewelry', 'Beauty'],
  },
  {
    name: 'Kids',
    subcategories: ['Boys', 'Girls', 'Baby', 'Toys', 'School'],
  },
  {
    name: 'Beauty',
    subcategories: ['Skincare', 'Makeup', 'Fragrance', 'Haircare', 'Tools'],
  },
  {
    name: 'Home & Decor',
    subcategories: ['Furniture', 'Bedding', 'Kitchen', 'Lighting', 'Art'],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Cotton Tee',
    price: 45,
    category: 'Men',
    subcategory: 'Clothing',
    image: 'https://picsum.photos/seed/men-tee/600/800',
    description: 'A high-quality cotton t-shirt with a modern fit.',
    rating: 4.5,
    reviews: 120,
  },
  {
    id: '2',
    name: 'Silk Evening Gown',
    price: 299,
    category: 'Women',
    subcategory: 'Clothing',
    image: 'https://picsum.photos/seed/women-dress/600/800',
    description: 'Elegant silk gown for special occasions.',
    rating: 4.8,
    reviews: 85,
  },
  {
    id: '3',
    name: 'Leather Chronograph',
    price: 180,
    category: 'Men',
    subcategory: 'Watches',
    image: 'https://picsum.photos/seed/watch/600/800',
    description: 'Classic leather strap watch with precision timing.',
    rating: 4.7,
    reviews: 210,
  },
  {
    id: '4',
    name: 'Designer Handbag',
    price: 450,
    category: 'Women',
    subcategory: 'Handbags',
    image: 'https://picsum.photos/seed/handbag/600/800',
    description: 'Luxury leather handbag with gold-tone hardware.',
    rating: 4.9,
    reviews: 45,
  },
  {
    id: '5',
    name: 'Kids Denim Jacket',
    price: 65,
    category: 'Kids',
    subcategory: 'Boys',
    image: 'https://picsum.photos/seed/kids-jacket/600/800',
    description: 'Durable and stylish denim jacket for kids.',
    rating: 4.4,
    reviews: 60,
  },
  {
    id: '6',
    name: 'Organic Face Serum',
    price: 85,
    category: 'Beauty',
    subcategory: 'Skincare',
    image: 'https://picsum.photos/seed/serum/600/800',
    description: 'Revitalizing face serum with natural ingredients.',
    rating: 4.6,
    reviews: 150,
  },
  {
    id: '7',
    name: 'Modern Velvet Sofa',
    price: 899,
    category: 'Home & Decor',
    subcategory: 'Furniture',
    image: 'https://picsum.photos/seed/sofa/600/800',
    description: 'Comfortable velvet sofa with a minimalist design.',
    rating: 4.7,
    reviews: 30,
  },
  {
    id: '8',
    name: 'Ceramic Table Lamp',
    price: 120,
    category: 'Home & Decor',
    subcategory: 'Lighting',
    image: 'https://picsum.photos/seed/lamp/600/800',
    description: 'Handcrafted ceramic lamp for a warm ambiance.',
    rating: 4.5,
    reviews: 95,
  },
];
